### ISSUE TITLE
Sink without accessKey & AccessSecret not supported

### ISSUE THREAD

**Issue by ioxFR** [serilog-contrib/Serilog.Sinks.AmazonS3#1]
Dear All,

I using this sink to stream logs in a AmazonS3.
In my configuration, authorization to AmazonS3 is directly handle via IAM to prevent generating each time accesskey and accesssecret for each environment.

In this context, sink should provide a method without accessKey and AccessId.

Have nice day,

Rgds

**Comment by SeppPenner** [comment]
I will try to integrate this but don't expect this until the end of this week as I have a lot of stuff to do.
https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html

**Comment by ioxFR** [comment]
Hi @SeppPenner ,

I finished the implementation on my side.
I currently testing it, i will submit you a pull request today or tomorrow.

Thanks

**Comment by ioxFR** [comment]
@SeppPenner implementation done, tested on my AWS tenant included for role based authorization to S3 from EC2.
#2 
I pushed also some other code enhancements and added an failureCallback.

Please feel free to comment

Thanks

**Comment by SeppPenner** [comment]
I will take a look at this in detail tonight. It looks good from a first look. The only thing I don't really agree with is the comment refactoring (This is mainly because my `Resharper` will kill your formatting changes after I press `CTRL+R+R` once...)

**Comment by ioxFR** [comment]
No problem, if you want i can revert the comments refractoring part or you can fix yourself as you using ghostdoc right?
Tell me and i can fix it.

**Comment by SeppPenner** [comment]
I will check if it's a problem and tell you.

**Comment by SeppPenner** [comment]
Fixed with https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/pull/2. I will create the new nuget package soon.

**Comment by SeppPenner** [comment]
The package is uploaded and will be available soon under https://www.nuget.org/packages/HaemmerElectronics.SeppPenner.Serilog.Sinks.AmazonS3/1.0.2
