### ISSUE TITLE
Find a way to inject  AmazonS3Client client in  the RollingFileSink in a dotnet core application

### ISSUE THREAD

**Issue by Abianue1** [serilog-contrib/Serilog.Sinks.AmazonS3#12]
In the RollingFileSink.cs
 `private async Task<PutObjectResponse> UploadFileToS3()`

The library creates a new instance of the AmazonS3Client
`new AmazonS3Client();`

Doing this would not get all the aws configured options at startup and this is especially bad for AWS using different IAM roles

For my fix, I Injected the IServiceProvider (I know this is not the best way)
so instead of creating a new instance,
I used
 `client = (AmazonS3Client)serviceProvider.GetService(typeof(IAmazonS3));`

**Comment by SeppPenner** [comment]
Yes, this needs an extension method for Serilog / AspNetCore. I will check this and see what I can do here.

**Comment by SeppPenner** [comment]
This should be fixed with https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/commit/1bc72a9fa5b5015a3f0bb088b9cc9e25c6a406e7 and in the next release.

**Comment by SeppPenner** [comment]
Version 1.1.0 should work here, you can now specifiy a `client` option of type `AmazonS3Client` in the logger configuration as first parameter.
