### ISSUE TITLE
Is it safe for multiple instances to write to the same log file?

### ISSUE THREAD

**Issue by profet23** [serilog-contrib/Serilog.Sinks.AmazonS3#15]
As per: https://github.com/serilog/serilog-sinks-file#shared-log-files

You need to enabled the `shared` flag in order to enable this with the file sinks mechanism. Is this neccessary/available for the AmazonS3 sink?   

Is it safe for multiple instances to write to the same log file in S3?

**Comment by SeppPenner** [comment]
I haven't tried this, but I would say currently not. The sink doesn't use the file sink anymore, but the periodic batching sink now. I will check this and see what I can do.

**Comment by SeppPenner** [comment]
The problem here is that the files are written and when the file is done, it will be uploaded to S3 and deleted. So, I wouldn't use the sink like this.

**Comment by SeppPenner** [comment]
I guess, the question is answered. If someone is willing to implement this feature, I will test it. But I don't want to implement it on my own...
