### ISSUE TITLE
Files Logging in project source itself too.

### ISSUE THREAD

**Issue by Vignesh-coder-coder** [serilog-contrib/Serilog.Sinks.AmazonS3#17]
File logging in A3 as well as project source itself. 
When I try to debug the project it creates the files in my local project source too.

**Comment by SeppPenner** [comment]
That is intended. What is not intended, is that the files are not deleted. I will try to add this soon.

**Comment by SeppPenner** [comment]
This will be added to the next version (1.1.2), fix is in https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/commit/8a407192058516a3275db6952a5943353d0d5587.

**Comment by SeppPenner** [comment]
Version 1.1.2 should be available soon.

**Comment by Vignesh-coder-coder** [comment]
Great Thanks.
