### ISSUE TITLE
Overwriting log file

### ISSUE THREAD

**Issue by Logikgate** [serilog-contrib/Serilog.Sinks.AmazonS3#20]
Hello!

I am attempting to use this package but it seems like it's just overwriting the log file in S3 each time a logging event happens. My setup is below, is there something I need to do to make it append to the file rather than overwrite it?

 ```
  loggerConfig.WriteTo.AmazonS3(
      "log.txt", 
      "bucket", 
      Amazon.RegionEndpoint.USEast2, 
      "key", 
      "secret", 
      Serilog.Events.LogEventLevel.Verbose, 
      null, 
      new Serilog.Formatting.Json.JsonFormatter());
```

**Comment by Logikgate** [comment]
Closing this since this seems to be a limitation of S3

**Comment by SeppPenner** [comment]
To be honest, I have never seen this behaviour, but thanks for the information.
