### ISSUE TITLE
Each time creates new log file in amazon S3

### ISSUE THREAD

**Issue by DelliBabuG** [serilog-contrib/Serilog.Sinks.AmazonS3#21]
Hi,
I am trying to log the errors in the same file every time, but it creates a new file each time I request.

Please help me to fix this

**Comment by SeppPenner** [comment]
Hi, this won't be possible, the AmazonS3 sink uses the sink under https://github.com/serilog/serilog-sinks-periodicbatching to provide events in batches and therefore writes one file per batch.

It's not really reasonable to write logs to one file only if you ask me:
- Your local file system is getting filled up (Assume a log file with 2 GB over a time) as the sink first writes logs to a local file and then pushes it to S3.
- You might loose data if your local file system is corrupt and your (big) log file is never sent to S3.
- Theoretically you can upload files up to 5TB to S3 (https://aws.amazon.com/de/blogs/aws/amazon-s3-object-size-limit/), but it will take a lot of time to upload and you also might loose data while transfering (Or the upload breaks and you will have to retry it again).
- S3 doesn't allow to append to a file directly (Check https://stackoverflow.com/questions/41783903/append-data-to-an-s3-object) --> Every change to your log file would need to either push the local file completely again to overwrite the one in S3, which limits your local file system as already described, or to download the file from S3 locally, append and overwrite the file in S3 again. Both operations are time-consuming and might get expensive (As you pay per up-and download in most cases in S3).

As a workaround for you (Nothing the sink can provide), you can aggregate your files with services like Amazon Elastic Map Reduce (https://aws.amazon.com/emr/) or maybe Amazon AWS Kinesis Firehose (As described in the linked Stackoverflow post as second answer).

I hope, that this helps you, but as described (Mainly of reason 3 as S3 doesn't allow to append to files), there is nothing I can do to change this behaviour right now.
