### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by stylesm** [serilog-contrib/Serilog.Sinks.AmazonS3#27]
I notice that the unit tests for this sink are quite broad.

They could perhaps be expanded into more specific tests.

A more specific test might have picked up on this bug for example https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3/pull/25

I'm happy to do this - just want to check it's a good idea before stepping on any toes.

**Comment by SeppPenner** [comment]
I believe that's a good idea, just go ahead :)

**Comment by SeppPenner** [comment]
I will close the issue now, just add some more test if you want to and I will check and merge them :)
