### ISSUE TITLE
Writing to folder inside s3

### ISSUE THREAD

**Issue by markg21** [serilog-contrib/Serilog.Sinks.AmazonS3#29]
I could not figure out a way to write to a specific folder inside the bucket using this project. It only writes directly inside the bucket.
Even forked it and manually edited the put request to use the file path but it just stopped writing altogether.
How do I do this?

**Comment by SeppPenner** [comment]
I need to check this as well, I can remember that it should work somehow...

**Comment by markg21** [comment]
Just found it myself. There's a parameter called bucketPath. Sorry for being silly and thanks for the effort.
