### ISSUE TITLE
How to make AmazonS3 available as a sink (WriteTo)

### ISSUE THREAD

**Issue by MarneeDear** [serilog-contrib/Serilog.Sinks.AmazonS3#3]
Thanks for this library.

I am trying to use it in my ASP.NET web app, but I can't find the AmazonS3 sink when I try to configure the logger.

I have:

- installed the nuget package
- Imported the namespaces Serilog and Serilog.Sinks
- Instantiated a LoggerConfiguration and tried to setup according to the documentation, but I don't have AmazonS3 available

![image](https://user-images.githubusercontent.com/5660628/66139014-7e754780-e5b4-11e9-869b-2704fc11c989.png)

I guess I am missing an import reference, but I don't know what it could be.

Thanks for your help.

**Comment by MarneeDear** [comment]
Ugh, I forgot to reference in my project dependencies. I had added the package to my global packages but didn't add it to the web project's references. Sorry and thanks.

**Comment by SeppPenner** [comment]
Ah okay :D
