### ISSUE TITLE
Dynamic S3 paths based on Time

### ISSUE THREAD

**Issue by ntr55** [serilog-contrib/Serilog.Sinks.AmazonS3#30]
Hello,

Is it possible to use dynamic path based on time 
(for example: {DateTime.UtcNow.Year}/{DateTime.UtcNow.Month}/{DateTime.UtcNow.Day}/log.log)?

(for an app that might not restart daily)

**Comment by SeppPenner** [comment]
I guess, this will not work right now, but I honestly haven't tested it yet.

**Comment by augustoproiete** [comment]
@ntr55 You should be able to use [Serilog.Sinks.Map](https://github.com/serilog/serilog-sinks-map) to wrap the AmazonS3 sink and dynamically set the filename.

e.g.:

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Map(_ => GetLogFileName(), (fileName, wt) =>
    {
        wt.AmazonS3(path: fileName, /* ... */)
    }, sinkMapCountLimit: 1)
    .CreateLogger();

// ...

static string GetLogFileName()
{
    var nowUtc = DateTime.UtcNow;
    return $"{nowUtc.Year}/{nowUtc.Month}/{nowUtc.Day}/log.log";
}
```

**Comment by SeppPenner** [comment]
@augustoproiete Ah, good to know. I haven't tested this yet (Nor have I seen this before to be honest) 😄

**Comment by SeppPenner** [comment]
I assume that this is solved. If not, just contact me again here.
