### ISSUE TITLE
Multiple files written per day even though Rolling Interval is set for Day

### ISSUE THREAD

**Issue by treysuiter** [serilog-contrib/Serilog.Sinks.AmazonS3#43]
Hello there. I have the S3 sink left at its default RollingInterval by Day but I am still getting multiple files written to the bucket per day with `_00X` appended to the name. I was under the assumption this would work like the File sink (which I have configured to roll per day and is working fine).  Code to configure logger is below. Thanks for any help!

```
.WriteTo.AmazonS3(
                    path:"logs.txt",
                    bucketName: "bucket-name",
                    endpoint: Amazon.RegionEndpoint.USEast2,
                    formatter: new JsonFormatter()
                    )
```

**Comment by treysuiter** [comment]
Looks like this is working as intended as S3 does not handle appending objects. Closing.

**Comment by SeppPenner** [comment]
> Looks like this is working as intended as S3 does not handle appending objects. Closing.

That is the indeed the reason. Sorry for my late reply.
