### ISSUE TITLE
RollingInterval stucks on RollingInterval.Minute!

### ISSUE THREAD

**Issue by alabady** [serilog-contrib/Serilog.Sinks.AmazonS3#44]
Try to rolling log file as daily but it's still rolling per minute,
tried with RollingInterval.Day and RollingInterval.Hour and RollingInterval.Month but no changes!
here's my configuration:
```
Log.Logger = new LoggerConfiguration()
                .WriteTo.Console()
                .WriteTo.AmazonS3(
                    "log.json",
                    "files-logs-prod-bucket-01/logs",
                    RegionEndpoint.EUCentral1,
                    "access-key",
                    "secret-key",
                    restrictedToMinimumLevel: LogEventLevel.Verbose,
                    outputTemplate: "",
                    new CultureInfo("ar-IQ"),
                    levelSwitch: levelSwitch,
                    rollingInterval: RollingInterval.Day,
                    encoding: Encoding.Unicode,
                    failureCallback: e => Console.WriteLine($"An error occured in my sink: {e.Message}")
                )
                .CreateLogger();
```

output files like this (Requests/Minute in file):
log2022022702_002.json
log2022022702_003.json
log2022022702_004.json

**Comment by SeppPenner** [comment]
What was the issue?

**Comment by Octavio9052** [comment]
I'm having this issue, It was working correctly, one log file per Day (using RollingInterval.Day), until recently after a redeployment. No change made to this loggerconfiguration...

**Comment by Octavio9052** [comment]
It seems I was able to fix it by modifying how I create new instance of the serilogger, previously I was creating many instances instead of just the one I need and reuse it. After changing that it started working again. I guess there was some change in a dependency that my redeployment grabbed, because it had been working just fine for over half a year.

Just leaving this comment in case anyone else has the same issue as me.

**Comment by alabady** [comment]
guys the issuse from S3 side!, the S3 dosen't allow append to exist file

**Comment by SeppPenner** [comment]
> guys the issuse from S3 side!, the S3 dosen't allow append to exist file

I don't think so. The files are not appended, you just can't use multiple instances of the logger in parallel (As the files are written locally pretty much immediately).

I mean, you're right, AWS S3 doesn't allow appending, but the library doesn't append data in S3.
