### ISSUE TITLE
[Question] How to configure Retained Log Count Limit?

### ISSUE THREAD

**Issue by genoher** [serilog-contrib/Serilog.Sinks.AmazonS3#53]
I have a question about whether the retainedLogCountLimit parameter could be configured similar to how it is configured with log files. 

I configured the rolling interval with daily, and I would like to retain only the last 60 days. auto delete the oldest files.

Thank you

I use the last version 1.4.0

**Comment by SeppPenner** [comment]
The same as for https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3/issues/59. It's not supported. I don't use the file sync (As it had problems with the file created callback handler), just some parts of it like the file name roller. The base sink is the batched log event sink.
