### ISSUE TITLE
need new option to set PutObjectRequest Property DisablePayloadSigning to true

### ISSUE THREAD

**Issue by jawand** [serilog-contrib/Serilog.Sinks.AmazonS3#55]
I am using Cloudflare R2 and they support few of the S3 APIs. But Cloudflare R2 does not currently support the Streaming SigV4 implementation used by AWSSDK.S3.

So, it would be nice to have an option to pass `DisablePayloadSigning = true` in `PutObjectRequest` 

https://developers.cloudflare.com/r2/examples/aws/aws-sdk-net/#upload-and-retrieve-objects

**Comment by SeppPenner** [comment]
Valid request. Sorry for the long delay...

**Comment by SeppPenner** [comment]
Fixed by https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3/issues/56
