### ISSUE TITLE
No files logged in S3 for lambda, but no errors thrown

### ISSUE THREAD

**Issue by alexgurman** [serilog-contrib/Serilog.Sinks.AmazonS3#57]
In our lambdas we can't get S3 logging to work, tried all possible options. The code works when run locally with dotnet-lambda-test-tool-6.0, as well as from ECS service, but not from lambda.

Deploying directly from Visual Studio 2022 using AWS Toolkit,, Publish to AWS Lambda option 

Attaching dummy lambda with sample code (.NET 6).
[DummyLambdaUncommon.zip](https://github.com/serilog-contrib/Serilog.Sinks.AmazonS3/files/11738864/DummyLambdaUncommon.zip)

**Comment by alexgurman** [comment]
specifying Time Zone on the lambda did it:

 "TZ": {
      "Type": "String",
      "Default": "America/Chicago"
    }

**Comment by SeppPenner** [comment]
> specifying Time Zone on the lambda did it:
> 
> "TZ": { "Type": "String", "Default": "America/Chicago" }

Sorry for the late reply. Great that you found it.
