### ISSUE TITLE
.Net 6 has error with version >1.29

### ISSUE THREAD

**Issue by LanceloteHK** [serilog-contrib/Serilog.Sinks.AmazonS3#62]
It will pop up "System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified." for any version > 1.29.
It needs to upgrade the project to .Net 7 if want to use the newest version. Is that .Net6 not longer supported for this project?

**Comment by SeppPenner** [comment]
Oh no, not again this issue :D I had this with another project already...

**Comment by SeppPenner** [comment]
Seems to be the same kind of issue as https://github.com/serilog-contrib/Serilog.Sinks.MicrosoftTeams.Alternative/issues/30.

**Comment by SeppPenner** [comment]
Version 1.5.3.0 (2024-12-26) removes support for Net6 as it is already deprecated.
